Python. Homework #1. Task #1. Вильданов Эмир
EmirVildanov/BasicProgramming4 pull request #2
Opened 2021-02-25 22:08 UTC by EmirVildanov

2021-03-01 10:25 UTC, areyde requested changes
Good work. I added some commentaries and asked you to rewrite some calculations to be done in one line.

2021-03-01 10:25 UTC, areyde commented on homework/hw1/task1/vector.py
> +        return sum([vector.coordinates[i] * self.coordinates[i] for i in range(self.dimension)])
Since we already had the second lecture, you now know the `zip` function. Rewrite this iteration with `zip`, it will be easier to read and shorter.

2021-03-01 10:25 UTC, areyde commented on tests/hw1/task1/test_vector.py
> +        self.assertEqual(1, Vector([1, 1, 1]).dot(Vector([0, 0, 1])))
_Optional: try to write a test case that catches the error when the dimensions are different. Specifically, try to catch a specific error message. This is important, because such testcases have a pretty specific syntaxis._

2021-03-01 10:25 UTC, areyde commented on homework/hw1/task1/matrix.py
> +                raise ValueError("Matrix rows must have the same length")
This looks a bit clumsy, and has the following problem: you first check if the second row is the same as the first, then if the third is the same as the second, etc., so in reality you are actually comparing everything with the first line. Sou you can write it much simpler by comparing every row with the first one.

_Optional: use the keyword `any` here._

2021-03-01 10:25 UTC, areyde commented on homework/hw1/task1/matrix.py
> +            return False
This is very difficult to read, becase the logic is hidden in several clauses. Write it so that it is easily read from top down. For example, use `any` or `all` keywords that check 1). the instance, 2). the dimensions, 3). the values.

That being said, I think, you do not need to check for dimensions here at all: it is already impicitly checked when comparing the values.

2021-03-01 10:25 UTC, areyde commented on homework/hw1/task1/matrix.py
> +        return Matrix(new_values)
This can be done in one expression, by appending the first `for` cycle to the end as well. It is not always preferable, but let's do it in this homework to practice.

2021-03-01 10:25 UTC, areyde commented on homework/hw1/task1/matrix.py
> +        return Matrix(new_values)
The same here — this can also be done in one expression.

2021-03-01 10:25 UTC, areyde commented on homework/hw1/task1/matrix.py
> +            raise ValueError("Matrix have different dimensions")
Spelling: `Matrices`.

2021-03-01 10:25 UTC, areyde commented on homework/hw1/task1/matrix.py
> +            raise ValueError("Matrix have different dimensions")
And a more correct way to say it would be something like: "these dimensions are incompatible for multiplication",

2021-03-01 10:25 UTC, areyde commented on homework/hw1/task1/matrix.py
> +        return Matrix(new_values)
Even this can be done in one expression. I will give you two hints to make it simpler and more readable:
1. Transpose the second matrix.
2. Represent the lines of matrices as `Vector` objects, and use the `dot` function from there.

2021-03-01 10:25 UTC, areyde commented on tests/hw1/task1/test_matrix.py
> +    def test_should_dot_two_matrices(self):
_Optional: I think, you can add some tests that catch errors also._

2021-03-03 18:55 UTC, EmirVildanov commented on homework/hw1/task1/matrix.py
> +            return False
I think it is important to put comparison of values field inside of `if` block as only the object of `Matrix` type has `values` field and it's easier for IDE identify `Matrix` fields.

2021-03-03 19:02 UTC, areyde commented on homework/hw1/task1/matrix.py
> +            return False
You can check the instance first, and return false. Everything that happens after this, already assumes that this is a Matrix. 

Alternatively, you can just request that the type of `other` is `Matrix`, and thus check the instance implicitly.

2021-03-04 08:43 UTC, areyde approved these changes
Great job!

2021-03-04 08:43 UTC, merged