Python. Homework #1. Task #2. Вильданов Эмир
EmirVildanov/BasicProgramming4 pull request #3
Opened 2021-02-28 10:20 UTC by EmirVildanov

2021-03-01 10:56 UTC, areyde requested changes
Nice job! Added some comments, the main ideological one is the behavious of `nl` function in Bash. Some of my comments are in italics and are optional: if you want to take some more time and do some more complex things, you can, but it is up to you.

2021-03-01 10:56 UTC, areyde commented on homework/hw1/task2/wc.py
> +        current_file_bytes = 0
Such cases can be written easier as: `a, b, c, = 0, 0, 0`.

2021-03-01 10:56 UTC, areyde commented on homework/hw1/task2/wc.py
> +            print("No such file")
When this is called with several files, this is not obvious. Please, specify the specific filepath.

2021-03-01 10:56 UTC, areyde commented on homework/hw1/task2/wc.py
> +            print(f"{current_file_lines} {current_file_words} {current_file_bytes} {filepath}")
Please, use `\t` so that the numbers are neatly placed under one another.

2021-03-01 10:56 UTC, areyde commented on tests/hw1/task2/test_wc.py
> +    def assert_stdout(self, file_names: List[str], expected_output, mock_stdout):
Please, add missing types.

2021-03-01 10:56 UTC, areyde commented on tests/hw1/task2/test_wc.py
> +    def assert_stdout(self, file_names: List[str], expected_output, mock_stdout):
In all test files.

2021-03-01 10:56 UTC, areyde commented on homework/hw1/task2/nl.py
> +                if line == "\n":
`nl` actually prints empty lines, without numbering them. Try it yourself.

2021-03-01 10:56 UTC, areyde commented on homework/hw1/task2/nl.py
> +                    f"{count} {line.rstrip()}",
Please, add `\t` like in `nl` in bash.

2021-03-01 10:56 UTC, areyde commented on homework/hw1/task2/nl.py
> +    elif len(sys.argv) > 2:
_Optional: `nl` actually works very peculiarly with several files. Try it yourself. Can you implement this?_

2021-03-01 10:56 UTC, areyde commented on homework/hw1/task2/wc.py
> +            print("No such file")
In all of your functions.

2021-03-01 10:56 UTC, areyde commented on homework/hw1/task2/head.py
> +        with open(file_name, "r") as f:
You don't need to write `"r"`, it is the default behaviour.

2021-03-01 10:56 UTC, areyde commented on homework/hw1/task2/head.py
> +            print("Second argument is not int")
Please, specify that the second arguemnt is the number of lines. Like, "The number of lines should be an integer". 

Because I thought I can input several files :)

2021-03-01 10:56 UTC, areyde commented on homework/hw1/task2/head.py
> +        print("Too many arguments")
Please, specify what arguments should be then.

2021-03-01 10:56 UTC, areyde commented on homework/hw1/task2/tail.py
> +        with open(file_name, "r") as f:
Do not need `"r"` here too.

2021-03-01 10:56 UTC, areyde commented on homework/hw1/task2/tail.py
> +        print("Specify the path to the file")
All the same commentaries as for `head`.

2021-03-04 09:03 UTC, areyde requested changes
Awesome job, just a couple of small fixes left.

2021-03-04 09:03 UTC, areyde commented on tests/hw1/task2/test_wc.py
> +        file_name = "file_that_do_not_exist"
"does" not exist :)

2021-03-04 09:03 UTC, areyde commented on homework/hw1/task2/nl.py
> +                        continue
No, `nl` prints empty lines, it just skips the numbering. That's why it is so weird! So it should print `\t` and `line` here.

2021-03-04 09:03 UTC, areyde commented on homework/hw1/task2/head.py
> +        print("Too many arguments. Syntax: head.py [MAX_LINES_OPTION] [FILE_PATH]")
The arguments are the other way around, no?

2021-03-04 09:03 UTC, areyde commented on homework/hw1/task2/head.py
>              for i, line in enumerate(f):
Let's write it as `while` since we still can. The reason is the following: you are trying to recreate typical `while` behaviour with `for`. `for` is usually aimed at iterating over the entire list, whil idiomatically, here you are doing a `while`.

2021-03-04 09:03 UTC, areyde commented on tests/hw1/task2/test_wc.py
> +        file_name = "file_that_do_not_exist"
here and everywhere else

2021-03-04 09:03 UTC, areyde commented on homework/hw1/task2/tail.py
> +        print("Too many arguments. Syntax: tail.py [MAX_LINES_OPTION] [FILE_PATH]")
Also here.

2021-03-04 10:01 UTC, EmirVildanov commented on homework/hw1/task2/head.py
>              for i, line in enumerate(f):
Isn't it much wierder to catch StopIteration in case when file consists of less lines than passed [MAX_LINES_OPTION] argument is?

2021-03-04 10:04 UTC, areyde commented on homework/hw1/task2/head.py
>              for i, line in enumerate(f):
Hm, that's also true. Well, if we can't think of a nicer way of doing this using `while` or `next`, then it is fine!

2021-03-04 10:36 UTC, areyde approved these changes
💯

2021-03-04 10:36 UTC, merged