Python. Homework #2. Task #1. Вильданов Эмир
EmirVildanov/BasicProgramming4 pull request #4
Opened 2021-03-01 17:55 UTC by EmirVildanov

2021-03-09 12:17 UTC, nbirillo requested changes
Great! Thank you a lot for tests

2021-03-09 12:17 UTC, nbirillo commented on homwork/hw2/task1/curry.py
> +from collections import Callable
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working

2021-03-09 12:17 UTC, nbirillo commented on homwork/hw2/task1/curry.py
> +    if "args" in fun_parameters:
It looks a little bit strange because it works for:
```
def foo(*args):
    pass
```
but does not work for this one:
```
def foo(*my_args):
    pass
```

2021-03-09 12:17 UTC, nbirillo commented on homwork/hw2/task1/curry.py
> +        passed_args = []
You can use the following trick:
```
passed_args = set(passed_args or [])
```

2021-03-09 12:17 UTC, nbirillo commented on homwork/hw2/task1/curry.py
> +            raise ValueError("Arity is smaller than passed arguments number")
You have the same code fragment above. Could you please add a new function maybe? or something else

2021-03-09 12:17 UTC, nbirillo commented on tests/hw2/task1/test_curry.py
> +        self.assertTrue("Arity can not be negative" in str(context.exception))
Could you please add some function that can extract an exception message from context by exception type?

2021-03-09 12:17 UTC, nbirillo commented on tests/hw2/task1/test_curry.py
> +        self.assertTrue("Arity can not be negative" in str(context.exception))
Also, you use the same error text in different tests. Could you please add some constants here?

2021-03-09 12:17 UTC, nbirillo commented on tests/hw2/task1/test_curry.py
> +class CurryTestCase(unittest.TestCase):
Maybe is it better to separate tests for curry and uncurry? Or at least move common data into constants

2021-03-10 20:53 UTC, EmirVildanov commented on tests/hw2/task1/test_curry.py
> +        self.assertTrue("Arity can not be negative" in str(context.exception))
May you explain please what do you mean by "extract message by exception type"? I wrote small function but I am not sure I understood you correctly

2021-03-12 08:54 UTC, nbirillo commented on tests/hw2/task1/test_curry.py
> +        self.assertTrue("Arity can not be negative" in str(context.exception))
Now it looks ok because you use consts with the function, thanks!

2021-03-12 08:56 UTC, nbirillo approved these changes
Great, thanks!

2021-03-12 08:56 UTC, merged