Python. Homework #2. Task #2. Вильданов Эмир
EmirVildanov/BasicProgramming4 pull request #5
Opened 2021-03-01 19:47 UTC by EmirVildanov

2021-03-04 19:11 UTC, EmirVildanov commented
Don't know how to fix mypy error yet

2021-03-09 12:19 UTC, nbirillo commented
Do you need help?

2021-03-11 19:27 UTC, EmirVildanov commented
@nbirillo No I think I have solved mypy problem through your last presentation

2021-03-12 08:52 UTC, nbirillo requested changes
Great, one small comment

2021-03-12 08:52 UTC, nbirillo commented on homework/hw2/task2/cache_decorator.py
> +    for k, v in kwargs.items():
I think you should sort `kwargs.items()`, because it can have a different order for the same dicts

2021-03-13 12:58 UTC, SpirinEgor approved these changes
A few small comments, but overall it works.

2021-03-13 12:58 UTC, SpirinEgor commented on homework/hw2/task2/cache_decorator.py
> +def make_arguments_list(args: Tuple, kwargs: Dict) -> Tuple:
I think this should be inside of `FunctionWithCache` because here you implement some logic that only cache knows. Since you don't use `self` inside it, you can mark it as a static method.

2021-03-13 12:58 UTC, SpirinEgor commented on homework/hw2/task2/cache_decorator.py
> +            return self._cache[make_arguments_list(args, kwargs)]
To avoid the double call to a function, it's better to store the result in a variable and then use it.

2021-03-13 12:58 UTC, merged