Python. Homework #2. Task #3. Вильданов Эмир
EmirVildanov/BasicProgramming4 pull request #6
Opened 2021-03-04 17:44 UTC by EmirVildanov

2021-03-09 12:35 UTC, nbirillo requested changes
Great, thanks! I have two little comments

2021-03-09 12:35 UTC, nbirillo commented on homework/hw2/task3/smart_args.py
> +import random
Please, delete unused imports

2021-03-09 12:35 UTC, nbirillo commented on homework/hw2/task3/smart_args.py
> +        return lambda func: smart_args(func)
It looks a little bit strange. Why did not you use:
```
return lambda func: smart_args(func, positional_args_on=positional_args_on)
```
?

2021-03-10 20:44 UTC, EmirVildanov commented on homework/hw2/task3/smart_args.py
> +        return lambda func: smart_args(func)
Cause writing `if` statement doesn't require a lot brain work. I fixed it)

2021-03-12 08:49 UTC, nbirillo approved these changes
Great!

2021-03-12 08:49 UTC, merged